### PR TITLE
Gradle port

### PR DESCRIPTION
**Pull request by liz3**
# Merge when reviewed

This Ports the projects dependency and build system from maven to gradle.

To build FAT JAR: `./gradlew shadowJar` OR on win: `gradlew.bat shadowJar`

To generate Docs: `./gradlew javadoc` OR on win: `gradlew.bat javadoc`

I used a node js script to convert dependencies
```js
const fs = require("fs");

let inDeps = false;
let inExclusion = false;
const text = fs.readFileSync("/Users/liz3/Desktop/SavageFactions/pom.xml", "UTF-8");
const depnds = [];
let current = null;
const split = text.split("\n");
split.forEach((element, index) => {
  if (element.includes("<dependencies>")) {
    inDeps = true;
  }
  if (element.includes("</dependencies>")) {
    depnds.push(current);
    inDeps = false;
    current = null;
  }
  if (!inExclusion) {
    if (element.includes("<dependency>") && inDeps) {
      if (current !== null) depnds.push(current);
      current = { excludes: [] };
    }
    if (element.includes("<groupId>") && current !== null && inDeps) {
      current.groupId = element.split("<groupId>")[1].split("</groupId>")[0];
    }
    if (element.includes("<artifactId>") && current !== null && inDeps) {
      current.artifactId = element
        .split("<artifactId>")[1]
        .split("</artifactId>")[0];
    }
    if (element.includes("<version>") && current !== null && inDeps) {
      current.version = element.split("<version>")[1].split("</version>")[0];
    }
    if (element.includes("<scope>") && current !== null && inDeps) {
      current.scope = element.split("<scope>")[1].split("</scope>")[0];
    }
  }
  if (element.includes("<exclusion>") && current !== null && inDeps) {
    inExclusion = true;
    const merge = `${split[index + 1]}${split[index + 2]}${split[index + 3]}`
    const groupId =merge
      .split("<groupId>")[1]
      .split("</groupId>")[0];
    const artifactId = merge
      .split("<artifactId>")[1]
      .split("</artifactId>")[0];
    current.excludes.push({ groupId, artifactId });
  }
  if (element.includes("</exclusion>") && current !== null && inDeps) {
    if (inExclusion) inExclusion = false;
  }
});

fs.writeFileSync("/Users/liz3/Desktop/SavageFactions/out.txt", depnds.map((dep) => {
    if(dep.scope && dep.scope === "system") return "";
    const path = `'${dep.groupId}:${dep.artifactId}:${dep.version}'`;
    const prefix = !dep.scope ? "implementation" : (dep.scope === "provided" ? "compileOnly" : "implementation")
    if(dep.excludes.length === 0) {
        return `${prefix} ${path}`
    } else {
        return `${prefix} (${path}) {
            ${dep.excludes.map(exclude => {
                return `exclude group: '${exclude.groupId}', module: '${exclude.artifactId}'`
            }).join("\n")}
        }`
    }
}).join("\n"))
```

### CODE REVIEW

**Comment by liz3** [comment]
Also fixes #170 which was an issue here to, the repository path was wrong

**Review by SvenjaReissaus — COMMENTED** [review]
I would just ask to keep the POM file, so we don't drop support for maven, because I think that as an Open Source project, we shouldn't "_limit_" the project behavior within different environments, so I think allowing others to still compile with Maven should be possible.

**Comment by liz3** [comment]
@SvenjaReissaus thats a bad practice, maven has major disadvantages.
Gradle doesnt need extra dependencies, while maven does so it would make building actually easier.
Further keeping both could result in a whole bunch of problems

**Comment by SvenjaReissaus** [comment]
I understand your concern, just saying that it'll be a rough turn for whoever uses this repository and has been used to compile in maven cause it's been in the developer community for little more time than Gradle has, and SavageFactions has been using it ever since I remember. I am totally in accordance and even like the idea of using Gradle from now on, so perhaps @ProSavage can give the final revision and merge this.

**Pull request merged**
