### PR TITLE
removed redundant null check/optimized isVanished in some cases

### PR DESCRIPTION
**Pull request by Darkmans1440**
**What type of PR is this?**  (Feature, Bug fix, Formatting etc.)

optimization/feature

**Link to relevant issue number(s), if any:**

**Explain your change(s):**

Removed unneeded null check when casting in setup() and an unneeded import. The isVanished() method was also optimized when the player is vanished by Essentials.

Added safeZoneTerritoryDisablePVP which mimics peacefulTerritoryDisablePVP.

**Why did you make these change(s)?**

because I felt like it.

**Is there anything we need to know for compatability?** (variable names, placeholders etc.)

there shouldn't be any compatibility issues.

### CODE REVIEW

**Comment by prosavage** [comment]
Yeah this looks good

**Comment by prosavage** [comment]
Assuming the FactionsEntityListener stuff is well tested?
The code it self looks good.

Can you seperate these PR's into a Vanish fix and the next.

**Review by liz3 — APPROVED** [review]
I briefly looked over it, i dont see any issues on this pr, only `player.getMetadata("vanished")` could possibly be null?

**Comment by prosavage** [comment]
@liz3 player.getMetadata is marked with @nonull tag.

**Pull request merged**
